<a href="https://colab.research.google.com/github/birusolankar/NumPy/blob/main/Numpy_array_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# np.array, np.zeros, np.full, np.arange, np.random.randint, np.shape,

In [2]:
# creating 1 dimensional numpy array
n1 = np.array([1,2,3,4,5])

In [20]:
n1*2

array([ 2,  4,  6,  8, 10])

In [3]:
type(n1)

numpy.ndarray

In [6]:
# creating two dimensional array
n2 = np.array([[1,2,3,5], [10,20,30,40]])
n2

array([[ 1,  2,  3,  5],
       [10, 20, 30, 40]])

In [7]:
type(n2)

numpy.ndarray

### creating numpy array with zeros


In [10]:
# creating numpy array with zeros
n3 = np.zeros([1,2])
n3

array([[0., 0.]])

In [12]:
n4 = np.zeros([5,5])
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Creating numpy array with same number using full method of numpy

In [14]:
n5 = np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [16]:
n6 = np.full((5,5),8)
n6

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

# Initialising numpy array within a range

In [17]:
n7 = np.arange(10,20)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
n8 = np.arange(10,100,10)
n8

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#Initialising numpy array with random number

In [23]:
n9 = np.random.randint(1,100,5)
n9

array([96, 37, 82, 55, 55])

# Checking the shape of numpy array

In [29]:
n2 = np.array([[1,2,3,5], [10,20,30,40]])
n2

array([[ 1,  2,  3,  5],
       [10, 20, 30, 40]])

In [30]:
n2.shape

(2, 4)

In [31]:
n2.shape = (4,2)
n2

array([[ 1,  2],
       [ 3,  5],
       [10, 20],
       [30, 40]])

In [38]:
array = np.array([[1,2,3,4,5,6], [10,20,30,40,50,60]])
array

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [39]:
array.shape

(2, 6)

In [44]:
array.shape = (4,3)
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

# vstack, hstack, column_stack

In [45]:
n1 = np.array([10,20,30,40])
n2 = np.array([50,60,70,80])

In [47]:
vstack = np.vstack((n1,n2))
vstack

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [49]:
hstack = np.hstack((n1,n2))
hstack

array([10, 20, 30, 40, 50, 60, 70, 80])

In [51]:
column_stack = np.column_stack((n1,n2))
column_stack

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

# intersect1d, setdiff1d

In [52]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([5,6,7,8,9,10,11])
print(n1)
print(n2)

[1 2 3 4 5 6]
[ 5  6  7  8  9 10 11]


In [55]:
# intersect1d----> gives the common element of the both the arrays

np.intersect1d(n1,n2)

array([5, 6])

In [57]:
# setdiff1d----> gives the unique element of the first array

np.setdiff1d(n1,n2)

array([1, 2, 3, 4])

In [58]:
np.setdiff1d(n2,n1)

array([ 7,  8,  9, 10, 11])

# Addition of array

In [59]:
n1 = np.array([10,20])
n2 = np.array([30,40])

In [61]:
np.sum([n1,n2])

100

In [63]:
np.sum([n1,n2], axis = 0)  # sums numbers vertically

array([40, 60])

In [65]:
np.sum([n1,n2], axis = 1) # sums numbers horizontally

array([30, 70])

# Numpy array mathematics
## Addition
## Substraction
## Multiplication
## Division
## Mean
## Median
## Standard Deviation

In [66]:
n1 = np.array([10,20,30,40])

# Addition

In [67]:
# Addition
n1 + 1

array([11, 21, 31, 41])

In [68]:
n1 + 100

array([110, 120, 130, 140])

# Substraction

In [69]:
n1 - 1

array([ 9, 19, 29, 39])

In [70]:
n1 - 100

array([-90, -80, -70, -60])

# Multiplication

In [71]:
n1*5

array([ 50, 100, 150, 200])

# Division

In [72]:
n1/10

array([1., 2., 3., 4.])

In [73]:
n1/20

array([0.5, 1. , 1.5, 2. ])

# Mean

In [74]:
n1 = np.array([10,20,30,40,50,60])
n1

array([10, 20, 30, 40, 50, 60])

In [75]:
np.mean(n1)

35.0

In [77]:
np.std(n1)

17.07825127659933

In [78]:
np.median(n1)

35.0

# Numpy save and load


In [79]:
n1 = np.array([10,20,30,40,50])
np.save('my_numpy',n1)

In [80]:
n2 = np.load('my_numpy.npy')

In [81]:
n2

array([10, 20, 30, 40, 50])