<a href="https://colab.research.google.com/github/birusolankar/NumPy/blob/main/Numpy_array_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# np.array, np.zeros, np.full, np.arange, np.random.randint, np.shape,

In [2]:
# creating 1 dimensional numpy array
n1 = np.array([1,2,3,4,5])

In [20]:
n1*2

array([ 2,  4,  6,  8, 10])

In [3]:
type(n1)

numpy.ndarray

In [6]:
# creating two dimensional array
n2 = np.array([[1,2,3,5], [10,20,30,40]])
n2

array([[ 1,  2,  3,  5],
       [10, 20, 30, 40]])

In [7]:
type(n2)

numpy.ndarray

### creating numpy array with zeros


In [10]:
# creating numpy array with zeros
n3 = np.zeros([1,2])
n3

array([[0., 0.]])

In [12]:
n4 = np.zeros([5,5])
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Creating numpy array with same number using full method of numpy

In [14]:
n5 = np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [16]:
n6 = np.full((5,5),8)
n6

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

# Initialising numpy array within a range

In [17]:
n7 = np.arange(10,20)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
n8 = np.arange(10,100,10)
n8

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#Initialising numpy array with random number

In [23]:
n9 = np.random.randint(1,100,5)
n9

array([96, 37, 82, 55, 55])

# Checking the shape of numpy array

In [29]:
n2 = np.array([[1,2,3,5], [10,20,30,40]])
n2

array([[ 1,  2,  3,  5],
       [10, 20, 30, 40]])

In [30]:
n2.shape

(2, 4)

In [31]:
n2.shape = (4,2)
n2

array([[ 1,  2],
       [ 3,  5],
       [10, 20],
       [30, 40]])

In [38]:
array = np.array([[1,2,3,4,5,6], [10,20,30,40,50,60]])
array

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [39]:
array.shape

(2, 6)

In [44]:
array.shape = (4,3)
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

# vstack, hstack, column_stack

In [45]:
n1 = np.array([10,20,30,40])
n2 = np.array([50,60,70,80])

In [47]:
vstack = np.vstack((n1,n2))
vstack

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [49]:
hstack = np.hstack((n1,n2))
hstack

array([10, 20, 30, 40, 50, 60, 70, 80])

In [51]:
column_stack = np.column_stack((n1,n2))
column_stack

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])